name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Build and test with Rspc
      run: |
        pwd
        cd docker/api/api
        gem install bundler:1.16.1
        pwd
        sudo aptitude install libpq-dev
        bundle install --quiet --jobs 4 --retry 3
        echo finish bundle install
        bundle exec rspec
